apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: aathishtest1
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image:  suryaprasaath/sag-app:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            initialDeploySeconds: 5
            periodSeconds: 5
            successThreshold: 1
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name:  mysecret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  mysecret
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name:  mysecret
              key: DB_DATABASE
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name:  mysecret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name:  mysecret
              key: DB_PORT
        - name: PORT
          valueFrom:
            secretKeyRef:
              name:  mysecret
              key: PORT
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
