apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-svc
  namespace: aathishtest1
spec:
  selector:
{{ toYaml .Values.labels | indent 4 }}
  type: {{ .Values.svc_type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: 30002
