apiversion: apps/v1
app_name: aathish-nodejs-application
labels:
  app: node-app
imageTag: suryaprasaath/sag-app:1.0
port: 3000
secretFile: mysecret
replicaCount: 1
svc_type: LoadBalancer
serverURL: ZGF0YWJhc2UtMS5jZnZscmx5bWt4NW0udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
dbuser: cmFnYXY=
dbpass: cmFnYXYxMjM0
dbname: dXNlckRC
dbport: MzMwNg==
hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40
